deployment:
  tasks:
    - export DEPLOYPATH=/home/zn011920/public_html/
    - /bin/rm -Rf $DEPLOYPATH/api $DEPLOYPATH/img
    - /bin/cp -Rf build/* $DEPLOYPATH
    - /bin/cp -R src/api src/img $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH