export default [
  {
    questionText: 'Which share had the largest difference between highest and lowest price over the last 12 months?',
    questionImage: '/static/images/material/reasoningTests/share-price-index.png',
    width: 350,
    answerOptions: [
      { answerText: 'Huver Co', isCorrect: false },
      { answerText: 'Drebs Ltd', isCorrect: false },
      { answerText: 'Fevs Plc', isCorrect: true },
      { answerText: 'Fauvers', isCorrect: false },
      { answerText: 'Steapars', isCorrect: false },
    ],
  },
  {
    questionText: 'What was yesterday’s cost difference between 50 shares in Fevs plc and 100 shares in Steapars?',
    questionImage: '/static/images/material/reasoningTests/share-price-index.png',
    width: 350,
    answerOptions: [
      { answerText: '€164,726', isCorrect: false },
      { answerText: '€251,163 ', isCorrect: false },
      { answerText: '€172,577', isCorrect: false },
      { answerText: '€164,045 ', isCorrect: true },
      { answerText: 'None of these', isCorrect: false },
    ],
  },
  {
    questionText: 'Today’s DrebsLtd share price represents a 40% increase on the price one month ago. What was the Drebs Ltd share price a month ago?',
    questionImage: '/static/images/material/reasoningTests/share-price-index.png',
    width: 350,
    answerOptions: [
      { answerText: '€22 ', isCorrect: false },
      { answerText: '€25.20', isCorrect: false },
      { answerText: '€12.68', isCorrect: false },
      { answerText: '€12.90', isCorrect: false },
      { answerText: '€12.86', isCorrect: true },
    ],
  },
  {
    questionText: 'If a driver travels an average of 4,250 miles per month driving only along motorways in an Xtam car, what is the predicted annual consumption of fuel (in gallons)?',
    questionImage: '/static/images/material/reasoningTests/fuel-comsumption.png',
    width: 353,
    answerOptions: [
      { answerText: 'Cannot say', isCorrect: false },
      { answerText: '1,500', isCorrect: true },
      { answerText: '125', isCorrect: false },
      { answerText: '150', isCorrect: false },
      { answerText: '1,250', isCorrect: false },
    ],
  },
  {
    questionText: 'A car dealership has £600,000 to spend and wants to buy equal numbers of the Taber and Ursa cars. What is the largest number of each type of car that can be ordered?',
    questionImage: '/static/images/material/reasoningTests/fuel-comsumption.png',
    width: 353,
    answerOptions: [
      { answerText: '27', isCorrect: false },
      { answerText: '48', isCorrect: false },
      { answerText: '19', isCorrect: false },
      { answerText: '21', isCorrect: true },
      { answerText: '22', isCorrect: false },
    ],
  },
  {
    questionText: 'What is the ratio of the cost of a Taber: Velvo: Xtam?',
    questionImage: '/static/images/material/reasoningTests/fuel-comsumption.png',
    width: 353,
    answerOptions: [
      { answerText: '2:4:5', isCorrect: false },
      { answerText: '1:4:6', isCorrect: false },
      { answerText: '1:3:5', isCorrect: true },
      { answerText: '2:3:5', isCorrect: false },
      { answerText: '1:2:3', isCorrect: false },
    ],
  },
  {
    questionText: 'Legal sector spending on IT hardware, IT software and IT consulting are all set to increase by the same amounts in Year 6 as they did from Year 4 to Year 5. Assuming this is the case, what is the total legal sector spend in Year 6 on these three IT areas combined?',
    questionImage: '/static/images/material/reasoningTests/it-spending.png',
    width: 340,
    answerOptions: [
      { answerText: '£75 million', isCorrect: false },
      { answerText: '£85 million', isCorrect: false },
      { answerText: '£95 million', isCorrect: false },
      { answerText: '£105 million', isCorrect: false },
      { answerText: '£110 million', isCorrect: true },
    ],
  },
  {
    questionText: 'For years 1 to 3 inclusive, by how much did Make Fit Ltd’s income from consultancy services differ from those of Pure Gap plc?',
    questionImage: '/static/images/material/reasoningTests/it-spending.png',
    width: 340,
    answerOptions: [
      { answerText: '£110 more', isCorrect: false },
      { answerText: '£110,000 less', isCorrect: false },
      { answerText: '£1,100,000 more', isCorrect: false },
      { answerText: '£110 less', isCorrect: false },
      { answerText: '£1,100,000 less', isCorrect: true },
    ],
  },
  {
    questionText: 'Which of the following statements is false regarding legal sector spending between Year 4 and projected Year 5?',
    questionImage: '/static/images/material/reasoningTests/it-spending.png',
    width: 340,
    answerOptions: [
      { answerText: 'IT consulting will increase by £5 million', isCorrect: false },
      { answerText: 'IT consulting will match that of year 2', isCorrect: false },
      { answerText: 'IT software will exceed IT consulting', isCorrect: false },
      { answerText: 'Spending on IT hardware will decline', isCorrect: true },
      { answerText: 'None of these', isCorrect: false },
    ],
  },
  {
    questionText: 'In which year(s) did Make Fit Ltd and Pure Gap plc’s combined IT consultancy income exceed £6million?',
    questionImage: '/static/images/material/reasoningTests/it-spending.png',
    width: 340,
    answerOptions: [
      { answerText: 'Year 1 and Year 4', isCorrect: false },
      { answerText: 'Only Year 4', isCorrect: true },
      { answerText: 'Year 1 and Year 3', isCorrect: false },
      { answerText: 'Only Year 3', isCorrect: false },
      { answerText: 'Year 3 and Year 4', isCorrect: false },
    ],
  },
  {
    questionText: 'If actual labour costs rise so as to halve their difference from the target, what will be the change in actual Gross Profit?',
    questionImage: '/static/images/material/reasoningTests/turnover-and-profit.png',
    width: 540,
    answerOptions: [
      { answerText: 'Falls by £4,500', isCorrect: true },
      { answerText: 'Rises by £4,500', isCorrect: false },
      { answerText: 'No overall effect', isCorrect: false },
      { answerText: 'Rises by £9,000', isCorrect: false },
      { answerText: 'Falls by £9,000', isCorrect: false },
    ],
  },
  {
    questionText: 'IKE Computers aim to grow monthly gross profit by 1.5%. If all costs remain constant, what will the sales turnover need to be in February to hit the target?',
    questionImage: '/static/images/material/reasoningTests/turnover-and-profit.png',
    width: 540,
    answerOptions: [
      { answerText: '£242,099', isCorrect: false },
      { answerText: '£277,987', isCorrect: true },
      { answerText: '£38,555', isCorrect: false },
      { answerText: '£274,299', isCorrect: false },
      { answerText: '£288,000', isCorrect: false },
    ],
  },
  {
    questionText: 'If IKE Computers employed eighty permanent employees in January who were on the same salary, what would have been the effect on labour costs if they had replaced twenty permanent employees with interim staff each on monthly salaries of £3,000?',
    questionImage: '/static/images/material/reasoningTests/turnover-and-profit.png',
    width: 540,
    answerOptions: [
      { answerText: 'Cannot tell', isCorrect: false },
      { answerText: 'Decrease of £130,000', isCorrect: false },
      { answerText: 'Decrease of £20,750', isCorrect: false },
      { answerText: 'Increase of £2,075', isCorrect: false },
      { answerText: 'Increase of £18,500', isCorrect: true },
    ],
  },
  {
    questionText: 'Which sector represents approximately 19% of the profits from the five sectors shown?',
    questionImage: '/static/images/material/reasoningTests/consulting-profits.png',
    width: 380,
    answerOptions: [
      { answerText: 'Leisure', isCorrect: false },
      { answerText: 'Manufacturing', isCorrect: false },
      { answerText: 'Retail', isCorrect: false },
      { answerText: 'Government', isCorrect: false },
      { answerText: 'Utilities', isCorrect: true },
    ],
  },
  {
    questionText: 'If the ratio of profit to turnover for Pacific Rim contracts was 2:15, what was the Government turnover in the Pacific Rim (in £100,000s)?',
    questionImage: '/static/images/material/reasoningTests/consulting-profits.png',
    width: 380,
    answerOptions: [
      { answerText: '36', isCorrect: false },
      { answerText: '27', isCorrect: false },
      { answerText: '270', isCorrect: true },
      { answerText: '360', isCorrect: false },
      { answerText: '540', isCorrect: false },
    ],
  },
  {
    questionText: 'Reyes Heslop had a target for Leisure profits to be a quarter of their total profits. Assuming profits in other areas remain the same, by how much did the Leisure profits miss this target?',
    questionImage: '/static/images/material/reasoningTests/consulting-profits.png',
    width: 380,
    answerOptions: [
      { answerText: '£1.8 million', isCorrect: false },
      { answerText: '£2.4 million', isCorrect: false },
      { answerText: '£2.7 million', isCorrect: false },
      { answerText: '£3.2 million', isCorrect: true },
      { answerText: '£3.4 million', isCorrect: false },
    ],
  },
  {
    questionText: 'A competitor wants to takeover Reyes Heslop and offers a price of 8 times current profits. Reyes Heslop shareholders reject this offer and suggest a price that is 20% higher, what is this suggested price?',
    questionImage: '/static/images/material/reasoningTests/consulting-profits.png',
    width: 380,
    answerOptions: [
      { answerText: '£79 million', isCorrect: false },
      { answerText: '£63 million', isCorrect: false },
      { answerText: '£628 million', isCorrect: false },
      { answerText: '£754 million', isCorrect: true },
      { answerText: '£502 million', isCorrect: false },
    ],
  },
  {
    questionText: 'What is the difference between direct sales and telesales across the five teams combined?',
    questionImage: '/static/images/material/reasoningTests/eastern-regional-sales.png',
    width: 380,
    answerOptions: [
      { answerText: '£10 million', isCorrect: false },
      { answerText: '£11 million', isCorrect: true },
      { answerText: '£12 million', isCorrect: false },
      { answerText: '£13 million', isCorrect: false },
      { answerText: '£14 million', isCorrect: false },
    ],
  },
  {
    questionText: 'If there are 50 direct sales and 65 telesales employees assigned to each of the Eastern region’s teams A-E, what are the average sales per sales employee for the lowest performing team in terms of overall sales (to the nearest £10,000)?',
    questionImage: '/static/images/material/reasoningTests/eastern-regional-sales.png',
    width: 380,
    answerOptions: [
      { answerText: 'Cannot tell from the data', isCorrect: false },
      { answerText: '£200,000 (direct); £340,000 (telesales)', isCorrect: false },
      { answerText: '£260,000 (direct); £260,000 (telesales)', isCorrect: true },
      { answerText: '£340,000 (telesales); £200,000 (direct)', isCorrect: false },
      { answerText: '£20,000 (direct sales); £30,000 (telesales)', isCorrect: false },
    ],
  },
  {
    questionText: 'If the Eastern Region’s total sales represent 26% of the total for all regions, what are the total sales across all regions (to the nearest £million)?',
    questionImage: '/static/images/material/reasoningTests/eastern-regional-sales.png',
    width: 380,
    answerOptions: [
      { answerText: '£124 million', isCorrect: false },
      { answerText: '£142 million', isCorrect: false },
      { answerText: '£142 million', isCorrect: false },
      { answerText: '£142 million', isCorrect: true },
      { answerText: '£620 million', isCorrect: false },
    ],
  },
  {
    questionText: 'What are the total sales targets for next year across all five teams if the target is set as a 20% and 10% increase in this year’s Direct Sales and Telesales respectively?',
    questionImage: '/static/images/material/reasoningTests/eastern-regional-sales.png',
    width: 380,
    answerOptions: [
      { answerText: 'Direct (£75 million); Telesales (£86 million)', isCorrect: false },
      { answerText: 'Direct Sales (£104 million); Telesales (£82 million)', isCorrect: false },
      { answerText: 'Direct (£82 million); Telesales (£104 million)', isCorrect: false },
      { answerText: 'Direct (£95 million); Telesales (£90 million)', isCorrect: false },
      { answerText: 'Direct (£90 million); Telesales (£94.6 million)', isCorrect: true },
    ],
  },
];
