import { v4 as uuid } from 'uuid';

export default [
  {
    id: uuid(),
    title: 'Data – Software Engineering Daily',
    path: 'https://softwareengineeringdaily.com/category/data/',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/software-engineering-daily/id1019576853?ls=1&mt=2#episodeGuid=https%3A%2F%2Fsoftwareengineeringdaily.com%2F%3Fp%3D10777',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9zb2Z0d2FyZWVuZ2luZWVyaW5nZGFpbHkuY29tL2NhdGVnb3J5L2RhdGEvZmVlZC8?sa=X&ved=0CAcQ27cFahcKEwjg2dHWnYXwAhUAAAAAHQAAAAAQCQ',
    spotify: 'https://open.spotify.com/show/6UCtBYL29hwhw4YbTdX83N?si=NBn5qN-ZRtCVD5SAwZQJqQ',
    description: 'Technical interviews about software topics.',
    media: '/static/images/resources/podcasts/software-engineering-daily.png',
  },
  {
    id: uuid(),
    title: 'Soft Skills Engineering',
    path: 'https://softskills.audio/',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/soft-skills-engineering/id1091341048?mt=2',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9zb2Z0c2tpbGxzLmF1ZGlvL2ZlZWQueG1s?sa=X&ved=0CAUQ27cFahcKEwjg2dHWnYXwAhUAAAAAHQAAAAAQCQ',
    spotify: 'https://open.spotify.com/show/59I1XnvAB9fQzSj9SIKCoI?si=pQPH1vuwQLOHbDvepEc8Fg',
    description: 'It takes more than great code to be a great engineer. Soft Skills Engineering is a weekly advice podcast for software developers about the non-technical stuff that goes into being a great software developer.',
    media: '/static/images/resources/podcasts/soft-skills.png',
  },
  {
    id: uuid(),
    title: 'Naked Security Podcast',
    path: 'https://nakedsecurity.sophos.com/',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/naked-security/id171426676',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5wb2R0cmFjLmNvbS9zWHFCbXN4TXJIaXg?sa=X&ved=0CBQQ27cFahcKEwjg1YSR3IrwAhUAAAAAHQAAAAAQAg',
    spotify: 'https://open.spotify.com/show/4AhwI3oHRgqO4v4Q5ZGaq9?si=nPPlgAKGQDqfYmVCTqgooA',
    description: 'We take an expert look at the latest cybersecurity incidents, how they happened, and why. Tune in weekly to learn what you can do to stop bad things from happening to you!',
    media: '/static/images/resources/podcasts/naked-security.jpg',
  },
  {
    id: uuid(),
    title: 'Job Hunter Podcast',
    path: 'https://anchor.fm/jobhunterpodcast',
    apple_podcasts: 'https://podcasts.apple.com/gb/podcast/job-hunter-podcast/id1538827375',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy8zZTgzMDEyNC9wb2RjYXN0L3Jzcw',
    spotify: 'https://open.spotify.com/show/0PBKxA65mzuJ6gPBBx2HaG',
    description: 'Come along and join the virtual careers fair as I ask the nation about their vocations. Feel free to follow the show on Facebook, Instagram, TikTok and Twitter @JobHunterPod, and Job Hunter Podcast on YouTube and LinkedIn. On Facebook you can also find our support group, or If you want to get in touch or be on the show drop us an email at Jobhunterpodcast@gmail.com',
    media: '/static/images/resources/podcasts/job-hunter.png',
  },
  {
    id: uuid(),
    title: 'The Career Rules You Didn’t Learn at School',
    path: 'https://hbr.org/2018/01/podcast-ideacast',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/the-career-rules-you-didnt-learn-at-school/id152022135?i=1000516955620',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cDovL2ZlZWRzLmhhcnZhcmRidXNpbmVzcy5vcmcvaGFydmFyZGJ1c2luZXNzL2lkZWFjYXN0/episode/dGFnOmF1ZGlvLmhici5vcmcsMjAwNi0wNS0wODppZGVhY2FzdC4wNzg4',
    spotify: 'https://open.spotify.com/episode/5naWIRH5QdvXE378yWXH8e?si=ccQbRl2yQCmttohinbG72Q',
    description: 'Gorick Ng, career advisor at Harvard, tried to learn about the world of work at an early age, helping his mother search job listings and send out resumes. To launch his own career, he studied hard in school, secured an Ivy League education, and landed a plum job. But he still found himself struggling – as many first-generation college graduates do – because he didn’t understand workplace norms in the way that his (mostly white, middle- to upper-class) peers did.  While they’d been taught how to network, angle for promotions, and “speak the language,” he was left to figure it out on his own. Now, Ng counsels young people on how to avoid those mistakes and take on their first job in a way that puts them on the fast-track to success. He’s the author of the book The Unspoken Rules: Secrets to Starting Your Career Off Right.',
    media: '/static/images/resources/podcasts/idea-cast.png',
  },
  {
    id: uuid(),
    title: 'Make it epic, w/will.i.am',
    path: 'https://mastersofscale.com/',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/47-make-it-epic-w-will-i-am/id1227971746?i=1000455551842',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9yc3MuYXJ0MTkuY29tL21hc3RlcnMtb2Ytc2NhbGU/episode/Z2lkOi8vYXJ0MTktZXBpc29kZS1sb2NhdG9yL1YwLzh0UXZhMEpsYjllNTZCRUxidGFzUWpkVndEVC05d1hrMjZOV0lYeE5BYW8?sa=X&ved=0CAcQuIEEahcKEwjg2dHWnYXwAhUAAAAAHQAAAAAQPA',
    spotify: 'https://open.spotify.com/episode/1T5RYrtmx4Y9ElcuScv2cw?si=S5lM4p56T6e5cDyNLHyx5A',
    description: 'What can entrepreneurs learn from a genre-crossing, multi-platinum musician? How to take a big opportunity — and leverage it into something epic. From his earliest days as a founding member of the Black Eyed Peas, will.i.am learned from mentors how to not only identify big opportunities but compound them. From the Super Bowl to the first iTunes commercial; from the founding of Beats and his tech company i.am+ to a song beamed back from Mars, his ability to bring stakeholders together to leverage partnerships and compound possibilities will inspire founders at any stage of scale. Cameo appearance: Jeremy Siegel (urban designer, Bjarke Ingels Group).',
    media: '/static/images/resources/podcasts/masters-of-scale.png',
  },
  {
    id: uuid(),
    title: 'The Recruiting Brainfood Podcast',
    path: 'https://recruitingbrainfood.podbean.com/',
    apple_podcasts: 'https://podcasts.apple.com/gb/podcast/the-recruiting-brainfood-podcast/id1463275155',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkLnBvZGJlYW4uY29tL3JlY3J1aXRpbmdicmFpbmZvb2QvZmVlZC54bWw?sa=X&ved=0CAYQ27cFahcKEwjg2dHWnYXwAhUAAAAAHQAAAAAQLw',
    spotify: 'https://open.spotify.com/show/3dFBspf9jXwpnJPLwSd72u?si=HQLIc0R4SFie0lJBKqDoCQ',
    description: '2 hosts, 3 guest, 60 minutes - it\'s your weekly dose of Recruiting Brainfood. My name is Hung Lee and every week I host a talkshow with leading figures in the staffing industry where we AI, future of work, recruitment agencies, diversity & inclusion, gig economy, recruiting technology, workplace culture and the rest.',
    media: '/static/images/resources/podcasts/brainfood.png',
  },
  {
    id: uuid(),
    title: 'TechStuff',
    path: 'https://www.iheart.com/podcast/105-techstuff-26941194/',
    apple_podcasts: 'https://podcasts.apple.com/ug/podcast/techstuff/id282795787',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5tZWdhcGhvbmUuZm0vdGVjaHN0dWZm?sa=X&ved=0CBgQ27cFahcKEwjg2dHWnYXwAhUAAAAAHQAAAAAQWQ',
    spotify: 'https://open.spotify.com/show/57wZcoxW8oNs5Mq7WZfTs7?si=rgeJ2Lq3SLGsdKCuo6t_mQ',
    description: 'TechStuff is a show about technology. And it’s not just how technology works. Join host Jonathan Strickland as he explores the people behind the tech, the companies that market it and how technology affects our lives and culture.',
    media: '/static/images/resources/podcasts/techstuff.jpg',
  },
  {
    id: uuid(),
    title: 'Find Your Dream Job: Insider Tips for Finding Work, Advancing your Career, and Loving Your Job',
    path: 'https://www.macslist.org/',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/find-your-dream-job-insider-tips-for-finding-work-advancing/id1047320599?mt=2',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9maW5keW91cmRyZWFtam9iLmxpYnN5bi5jb20vcnNz?sa=X&ved=0CAMQ4aUDahcKEwjYyrOm2IrwAhUAAAAAHQAAAAAQAQ',
    spotify: 'https://open.spotify.com/show/3atQnGqtk1o4XxJQ3CArz2?si=3LqZPLuhRrq47zJHxUQ4Mg',
    description: 'Build a career that matters to you with job search strategies and career advice from Find Your Dream Job. Every week, we share insider secrets and job search tips on how to get a great job and develop a purposeful career. Looking for your first job, searching for direction in your career, or just need tools to find a job? Join Mac Prichard, the Mac\'s List team, and our expert guests every week for job search inspiration, empathy, and actionable advice to help you find work that matters! Find out more at https://www.macslist.org/podcast',
    media: '/static/images/resources/podcasts/dream-job.png',
  },
  {
    id: uuid(),
    title: 'TribeTech Podcast',
    path: 'https://audioboom.com/channels/5010614',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/tribe-tech-podcast/id1486869907?uo=4',
    google_podcasts: 'https://podcasts.google.com/feed/aHR0cHM6Ly9hdWRpb2Jvb20uY29tL2NoYW5uZWxzLzUwMTA2MTQucnNz',
    spotify: 'https://open.spotify.com/show/2Myw2A1y8odyuInvLwgbYl',
    description: 'Are women and ethnic minorities avoiding the tech sector and where on earth would you find AI created cupcakes? Former broadcast journalists and tech enthusiasts Robert Hillier and Feyaza Khan (who are also married) help showcase the brilliant innovation in the South West - listen in now!',
    media: '/static/images/resources/podcasts/tribe-tech.png',
  },
  {
    id: uuid(),
    title: 'will.i.am: The Future of Social Media and Artificial Intelligence',
    path: 'https://www.oprah.com/app/supersoul-sunday-full-episodes.html',
    apple_podcasts: 'https://podcasts.apple.com/us/podcast/will-i-am-future-social-media-artificial-intelligence/id1264843400?i=1000412961429',
    google_podcasts: 'https://open.spotify.com/episode/0iw8WvMzZ49W3CyUSx7uCW?si=3QJeQ7I7R0elGn2XrLoE6A',
    spotify: '',
    description: 'Grammy-winning musician, producer, tech entrepreneur, author and philanthropist will.i.am is best known as the founder of the Black Eyed Peas. He shares why he\'s shifting away from making music and has been focusing his energy on using technology to create a better future through artificial intelligence and robotics. Oprah and will.i.am have a conversation about the dangers of technology, the era of social media, and how people have become "digitally rude." With a passion for giving back to underserved communities, will.i.am explains why he believes the key to ending poverty begins with education, particularly in the areas of science, technology, engineering and math (STEM). The artist also reveals why he believes artificial intelligence can be used as a tool to serve humanity and actually make us more humane. Will.i.am says, "For a long time, we\'ve ignored our God-given technology: spirituality."',
    media: '/static/images/resources/podcasts/super-soul.jpg',
  },
];
